//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebEstate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class properties_estate
    {
        public int property_id { get; set; }
        public string rentORsell { get; set; }
        public Nullable<int> bedrooms { get; set; }
        public Nullable<int> bathrooms { get; set; }
        public string description { get; set; }
        public string city_area { get; set; }
        public System.DateTime creation_date { get; set; }
        public string price { get; set; }
    }
}
